"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class dcmpc_reward_lcmt(object):
    __slots__ = ["survival_time"]

    __typenames__ = ["float"]

    __dimensions__ = [None]

    def __init__(self):
        self.survival_time = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(dcmpc_reward_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">f", self.survival_time))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != dcmpc_reward_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return dcmpc_reward_lcmt._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = dcmpc_reward_lcmt()
        self.survival_time = struct.unpack(">f", buf.read(4))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if dcmpc_reward_lcmt in parents: return 0
        tmphash = (0x3fbf0985e32010ba) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if dcmpc_reward_lcmt._packed_fingerprint is None:
            dcmpc_reward_lcmt._packed_fingerprint = struct.pack(">Q", dcmpc_reward_lcmt._get_hash_recursive([]))
        return dcmpc_reward_lcmt._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

