"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class dcmpc_reward_lcmt(object):
    __slots__ = ["reward", "steady_state"]

    __typenames__ = ["float", "boolean"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.reward = 0.0
        self.steady_state = False

    def encode(self):
        buf = BytesIO()
        buf.write(dcmpc_reward_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">fb", self.reward, self.steady_state))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != dcmpc_reward_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return dcmpc_reward_lcmt._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = dcmpc_reward_lcmt()
        self.reward = struct.unpack(">f", buf.read(4))[0]
        self.steady_state = bool(struct.unpack('b', buf.read(1))[0])
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if dcmpc_reward_lcmt in parents: return 0
        tmphash = (0x6bacd20dec674b08) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if dcmpc_reward_lcmt._packed_fingerprint is None:
            dcmpc_reward_lcmt._packed_fingerprint = struct.pack(">Q", dcmpc_reward_lcmt._get_hash_recursive([]))
        return dcmpc_reward_lcmt._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

